version: "3.8"
services:
    tensorboard:
        image: dl-tensorboard
        build:
            context: ./
            dockerfile: tensorboard.Dockerfile
        ports:
            - 6006:6006
        volumes:
            - /jupyter:/jupyter
        command:
            [
                "tensorboard",
                "--logdir=/jupyter",
                "--port=6006",
                "--bind_all",
            ]

    jupyter-server:
        image: dl-jupyter
        init: true
        build:
            context: ./
            dockerfile: jupyter.Dockerfile
        env_file: ./.env
        ports:
            - 8888:8888
        volumes:
            - /jupyter:/jupyter
        command:
            [
                "jupyter",
                "notebook",
                "--ip=*",
                "--port=8888",
                "--allow-root",
                "--notebook-dir=/jupyter",
            ]